/* Read-only companion: source text, original key and editorial review never share a key field. */
(()=>{'use strict';
const D=window.HS2_REVIEW,$=s=>document.querySelector(s),esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!D){$('#questions').textContent='Không mở được review-data.js. Giữ nguyên thư mục hs2 khi cập nhật.';return;}
const norm=t=>String(t??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().trim();
const refMap=new Map(D.references.map(r=>[r.id,r]));
const labels={agrees:'Khớp khóa',clarified:'Cần hiểu đúng phạm vi',corrected:'Đính chính',ambiguous:'Đề / phương án mơ hồ','needs-context':'Cần thêm điều kiện',convention:'Phụ thuộc quy ước','missing-context':'Thiếu chú giải'};
const originLabels={matched:'Đã có cùng câu / biến thể chữ ở bank gốc',equivalent:'Có câu tương đương ở bank gốc','not-found':'Chưa thấy cùng câu trong bản bank gốc'};
const modeLabels={expanded:'Có ý luyện bổ sung',reused:'Tái sử dụng ý luyện hiện có',held:'Không chấm khi thiếu dữ kiện'};
const appBase=window.HS2_APP_URL||new URL('../index.html',location.href).href;
function appLink(n,count=3,study=false){const u=new URL(appBase);u.searchParams.set('hs2',String(n));u.searchParams.set('count',String(count));if(study)u.searchParams.set('view','study');return u.href;}
function urlOf(ref){try{const u=new URL(ref.url,appBase);return /^https?:$/.test(u.protocol)?u.href:'';}catch(_){return '';}}
function references(ids){return [...new Set(ids)].map(id=>{const r=refMap.get(id),u=r&&urlOf(r);return u?`<li><a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a></li>`:'';}).join('');}
function originalRecordText(r){return [r.question,...(r.options||[]),...(r.statements||[]).map((s,i)=>`${i+1}. ${s.text} — khóa nguồn: ${s.correct?'Đ':'S'}`),'Khóa nguồn: '+(r.options?String.fromCharCode(65+Number(r.answer)):typeof r.answer==='string'?r.answer:'Xem từng mệnh đề')].join('\n').replace(/<br\s*\/?>/gi,'\n').replace(/<sub>(.*?)<\/sub>/gi,'_$1').replace(/<sup>(.*?)<\/sup>/gi,'^$1').replace(/<[^>]*>/g,'');}
let page=0,show=false;const size=8;
const stats=D.stats;
$('#overview').innerHTML=`<div class="stat"><b>${stats.documentItems}</b><span>mục có thật trong tài liệu</span></div><div class="stat"><b>${stats.addedQuestions}</b><span>câu luyện mới + ý học</span></div><div class="stat"><b>${stats.collectionPracticeQuestions}</b><span>ý luyện liên quan, đã gộp lặp</span></div>`;
$('#scopeNotes').innerHTML=D.notes.map(x=>`<p>${esc(x)}</p>`).join('')+`<p><strong>Bank gốc:</strong> ${stats.sourceTextMatches} cùng câu / biến thể chữ, ${stats.sourceEquivalent} tương đương, ${stats.sourceNotFound} chưa thấy cùng toàn bộ câu trong các tệp đã kiểm tra. <strong>NMNRT:</strong> giữ nguyên 732 câu; bổ sung ${stats.addedQuestions}, tổng ${stats.totalQuestions}. Mục thiếu chú giải: 126.</p>`;
$('#practiceAll').href=appLink('all',10);$('#backLink').href=appBase;
function card(q){
 const attention=q.reviewStatus!=='agrees';const images=q.images.map(name=>`<figure class="figure"><img src="${esc(window.HS2_IMAGES?.[name]||'images/'+name)}" alt="Hình nguyên bản đi kèm câu ${q.number}" loading="lazy"><figcaption>Hình trong đề cương · câu ${q.number}${q.number===126?' · không có chú giải cột trắng/nâu trong ảnh gốc':''}</figcaption></figure>`).join('');
 const opts=q.kind==='mcq'?`<ul class="original-options">${q.options.map((s,i)=>`<li>${esc(q.number===5&&i===0?'A. '+s:s)}</li>`).join('')}</ul>`:q.kind==='tf'?`<ol class="statements" type="a">${q.statements.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`:'';
 const origin=q.legacyMatches.length?`<ul>${q.legacyMatches.map(m=>`<li><code>${esc(m.uid)}</code> · <a href="${esc(window.HS2_SITE_URL?new URL(m.page,window.HS2_SITE_URL).href:m.pageURL)}" target="_blank" rel="noopener noreferrer">${esc(m.page)}</a><br>${m.manualReason?esc(m.manualReason):'Đã đối chiếu đề và các phương án/mệnh đề.'}<details><summary>Xem bản ghi trong ${esc(m.file)}</summary><pre class="source-record">${esc(originalRecordText(m.originalRecord))}</pre><p>SHA-256 của tệp nguồn: <code>${esc(m.sha256)}</code></p></details></li>`).join('')}</ul>`:'<p>Không tìm thấy cùng câu trong ba bản chụp nguồn đã kiểm tra. Đây không phải kết luận rằng không tồn tại ở bất cứ phiên bản hay nơi nào khác.</p>';
 return `<article class="panel question ${attention?'attention':''}" id="q${q.number}" data-number="${q.number}"><header class="question-head"><h2>Câu ${q.number}</h2><span class="pill ${q.reviewStatus==='agrees'?'good':q.reviewStatus==='missing-context'?'danger':'caution'}">${esc(labels[q.reviewStatus])}</span></header><code class="question-code">${esc(q.code)} · ${q.kind==='mcq'?'Chọn A–D':q.kind==='tf'?'Đúng / sai':'Tự luận'}</code><p class="source-stem">${esc(q.stem)}</p>${images}${opts}<p class="match-line">${esc(originLabels[q.legacyStatus])} · ${esc(modeLabels[q.nmnrtStatus])}</p><details class="answer" ${show?'open':''}><summary>Đáp án & lí do</summary><div class="answer-body"><p class="source-key"><span>Khóa in trong tài liệu — giữ nguyên để đối chiếu</span>${esc(q.sourceAnswer)}</p><p class="review-key"><span>Kết luận rà soát của NMNRT</span>${esc(q.reviewedAnswer)}</p><p class="answer-note">${esc(q.explanation)}</p>${q.practiceIds.length?`<div class="practice-area"><p class="fine">${esc(q.practiceRelation)}</p><div class="actions"><a class="btn primary" href="${esc(appLink(q.number,3))}">Luyện ${Math.min(3,q.practiceIds.length)} ý liên quan →</a><a class="btn" href="${esc(appLink(q.number,1,true))}">Học ý liên quan</a></div><details class="origin"><summary>Các ý luyện liên kết (${q.practiceIds.length})</summary><ul>${q.practiceLinks.map(c=>`<li>${esc(c.prompt)} <span class="pill">${c.new?'Mới':'Đã có'} · Lớp ${c.grade}</span><br><code>${esc(c.id)}</code></li>`).join('')}</ul></details></div>`:'<p class="review-key">Chưa đưa câu gốc này vào chấm tự động. Cần bổ sung chú giải hình trước.</p>'}<details class="origin"><summary>Vị trí trong bank gốc & nguồn đối chiếu</summary><div>${origin}<p>Lí do và các giới hạn ở trên do NMNRT biên soạn. Tài liệu tham khảo hỗ trợ nguyên lí, không xác nhận khóa của giáo viên.</p><ul class="refs">${references(q.referenceIds)}</ul></div></details></div></details></article>`;
}
function render(){const text=norm($('#search').value),filter=$('#filter').value,kind=$('#kind').value;const no=text.match(/^(?:cau\s*)?(\d+)$/);let rows=D.questions.filter(q=>(kind==='all'||kind===q.kind)&&(!text||(no?q.number===Number(no[1]):norm(q.code+' '+q.stem+' '+q.body+' '+q.reviewedAnswer+' '+q.explanation).includes(text))));
 rows=rows.filter(q=>filter==='all'||filter==='attention'&&q.reviewStatus!=='agrees'||filter==='corrected'&&['corrected','ambiguous','convention'].includes(q.reviewStatus)||filter==='missing-context'&&q.reviewStatus==='missing-context'||filter==='not-found'&&q.legacyStatus==='not-found'||filter===q.nmnrtStatus);
 const pages=Math.max(1,Math.ceil(rows.length/size));page=Math.max(0,Math.min(page,pages-1));
 $('#questions').innerHTML=rows.length?rows.slice(page*size,(page+1)*size).map(card).join(''):'<div class="panel empty">Không thấy câu phù hợp. Thử số câu hoặc xóa bộ lọc.</div>';
 $('#resultCount').textContent=`${rows.length} / ${D.questions.length} mục · trang ${page+1}/${pages}. Số câu giữ theo đề gốc.`;
 $('#pageCount').textContent=`${page+1} / ${pages}`;$('#prev').disabled=page===0;$('#next').disabled=page>=pages-1;
 $('#showAnswers').textContent=show?'Thu đáp án trang này':'Hiện đáp án trang này';$('#showAnswers').setAttribute('aria-pressed',String(show));
}
['search','filter','kind'].forEach(id=>$('#'+id).addEventListener(id==='search'?'input':'change',()=>{page=0;render();}));
$('#clearSearch').onclick=()=>{$('#search').value='';$('#filter').value='all';$('#kind').value='all';page=0;render();};
$('#showAnswers').onclick=()=>{show=!show;document.querySelectorAll('.answer').forEach(el=>el.open=show);$('#showAnswers').textContent=show?'Thu đáp án trang này':'Hiện đáp án trang này';$('#showAnswers').setAttribute('aria-pressed',String(show));};
$('#prev').onclick=()=>{page--;render();$('#resultCount').scrollIntoView({block:'start'});};$('#next').onclick=()=>{page++;render();$('#resultCount').scrollIntoView({block:'start'});};
const initial=new URLSearchParams(location.search).get('q')||location.hash.match(/^#q(\d+)$/)?.[1];if(initial){$('#search').value=initial;show=true;}render();
})();
